[package]
name = "integration_tests_dependency"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
natrix = {path = "../natrix", features = ["nightly"]}
log = {version = "0.4", features = ["max_level_trace", "release_max_level_trace"]}
