[package]
name = "dagger_pipeline"
version = "0.1.0"
edition = "2024"

[dependencies]
dagger-sdk = "0.18.11"
eyre = "0.6.12"
serde_json = "1.0.140"
tokio = { version = "1.45.1", features = ["macros", "rt-multi-thread"] }
uuid = { version = "1.17.0", features = ["v4"] }

[lints]
workspace = true
