[workspace]
resolver = "2"
members = [
    "natrix_shared",
    "natrix_macros",
    "natrix",
    "natrix-cli",
    "integration_tests",
    "bench_project", "integration_tests_dependency",
]

[profile.release]
opt-level = "z"
codegen-units = 1
lto = "fat"
panic = "abort"
strip = "symbols"
