[package]
name = "natrix"
version = "0.1.0"
edition = "2024"

description = "Rust-First frontend framework."
license = "MIT"
repository = "https://github.com/vivax3794/natrix"

readme = "../README.me"

[dependencies]
wasm-bindgen = {version= "0.2.100", features=["enable-interning"]}
web-sys = { version = "0.3.77", features = ["Comment", "Element", "Event", "Text", "Document", "Window", "HtmlElement"] }

natrix_macros = {path = "../natrix_macros", version="0.1.0"}

itoa = { version = "1.0.14" }
nohash-hasher = "0.2.0"
ryu = "1.0.20"

wasm-bindgen-futures = { version = "0.4.50", optional = true }
gloo = { version = "0.11.0", optional = true, default-features = false, features=["timers", "futures"]}
ouroboros = { version = "0.18", optional = true }
futures = { version = "0.3.31", optional = true, default-features = false }

[dev-dependencies]
wasm-bindgen-test = {version="0.3.50"}

[build-dependencies]
rustversion = "1.0.19"

[features]
default = ["async"]

nightly = []
async = ["dep:wasm-bindgen-futures", "dep:futures", "dep:ouroboros", "dep:gloo"]
ergonomic_ops = []
