[graph]
targets = [
    "wasm32-unknown-unknown",
]
all-features = true

[licenses]
allow = [
    "MIT",
    "Zlib",
    "Unicode-3.0",
    "BSL-1.0",
]

[bans]
multiple-versions = "deny"
wildcards = "deny"
