[graph]
targets = [
    "wasm32-unknown-unknown",
]
all-features = true

[advisories]
ignore = [
    { id="RUSTSEC-2024-0436", reason="While not maintained, its still in used by major rust libraries like itertools, so I think we are good"}
]

[licenses]
allow = [
    "MIT",
    "Zlib",
    "Unicode-3.0",
    "BSL-1.0",
]

[bans]
multiple-versions = "deny"
wildcards = "deny"
