[package]
name = "integration_tests"
version = "0.1.0"
edition = "2024"

[dependencies]
natrix = {path = "../natrix"}

[dev-dependencies]
thirtyfour_sync = { version = "0.27.1", default-features = false }
