[package]
name = "natrix_macros"
version = "0.1.0"
edition = "2024"

description = "Macros for natrix"
license = "MIT"
repository = "https://github.com/vivax3794/natrix"

[lib]
proc-macro = true

[dependencies]
natrix_shared = {path = "../natrix_shared"}

proc-macro2 = {version="1.0.83", default-features = false}
quote = {version="1.0.35", default-features = false}
syn = { version = "2.0.87", default-features = false, features=["derive", "proc-macro", "parsing", "printing", "full", "clone-impls"]}
template-quote = "0.4.0"

[build-dependencies]
natrix_shared = {path = "../natrix_shared"}
