[package]
name = "natrix_macros"
version = "0.1.0"
edition = "2024"

description = "Macros for natrix"
license = "MIT"
repository = "https://github.com/vivax3794/natrix"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = {version="1.0.75", default-features = false}
quote = {version="1.0.35", default-features = false}
syn = { version = "2.0.52", default-features = false, features=["derive", "proc-macro", "parsing", "printing", "full", "clone-impls"]}
template-quote = ">=0.3.0, <0.5"
