[graph]
targets = [
    "wasm32-unknown-unknown",
]
all-features = true
exclude-dev = true

[licenses]
allow = [
    "MIT",
    "Zlib",
    "Unicode-3.0",
    "BSL-1.0",
]

[bans]
multiple-versions = "deny"
wildcards = "deny"
skip = [
    # https://github.com/taiki-e/pin-project/pull/367
    { crate = "syn@2.0.119", reason = "Some dependencies have not updated to syn v3." }
]
