[package]
name = "natrix_shared"
version = "0.3.0"
edition = "2024"
license = "MIT"
description = "Shared code for Natrix framework."

[lints]
workspace = true

[dependencies]
bincode = { version = "2.0.1", optional = true }

[features]
macros = ["dep:bincode"]
