[package]
name = "natrix_shared"
version = "0.3.0"
edition = "2024"
license = "MIT"
description = "Shared code for Natrix framework."

[lints]
workspace = true

[dependencies]
serde = { workspace = true, features = ["derive", "std"], optional = true }
serde_json = { workspace = true, optional = true }

[features]
macros = ["dep:serde", "dep:serde_json"]
