[book]
authors = ["Viv"]
language = "en"
src = "src"
title = "Natrix"

[rust]
edition = "2024"

[output.html.playground]
runnable = false

[preprocessor.rustdoc-links]
after = ["links"]
renderers = ["html"]
fail-on-warnings = "always"

[preprocessor.rustdoc-links.build]
all-features = true
