[book]
authors = ["Viv"]
language = "en"
multilingual = false
src = "src"
title = "Natrix"

[rust]
edition = "2024"

[output.html.playground]
runnable = false

[preprocessor.callouts]
[preprocessor.rustdoc-link]
manifest-dir = "../crates/natrix"
after = ["links"]
cargo-features = ["all"]
cache-dir = "../target/doc-cache"
fail-on-warnings = "always"
#rust-analyzer-timeout = 300 # 5 minutes
