[graph]
all-features = true
exclude-dev = true

[licenses]
allow = [
    "MIT",
    "Zlib",
    "Apache-2.0",
    "MPL-2.0",
    "ISC",
    "CC0-1.0",
    "BSD-3-Clause",
    "BSL-1.0",
    "Unicode-3.0"
]

[bans]
multiple-versions = "warn"
wildcards = "deny"
