name: Publish mdBook

on:
  push:
    branches:
      - master
    paths:
      - "docs/**"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
      FORCE_COLOR: 1

    steps:
      - uses: earthly/actions/setup-earthly@v1
        with:
          version: v0.8.13
      - uses: actions/checkout@v3
      - name: Docker Login
        run: docker login --username "$DOCKERHUB_USERNAME" --password "$DOCKERHUB_TOKEN"
      - name: Run build
        run: earthly --org vivax3794 --sat natrix --ci --github-annotations ./docs+build-book
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/book

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
