name: Run Checks

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  run_ci:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
      FORCE_COLOR: 1

    steps:
      - uses: earthly/actions/setup-earthly@v1
        with:
          version: v0.8.13
      - uses: actions/checkout@v3
      - name: install earthly
      - name: Docker Login
        run: docker login --username "$DOCKERHUB_USERNAME" --password "$DOCKERHUB_TOKEN"
      - name: Run build
        run: earthly --org vivax3794 --sat natrix --ci --github-annotations +all
