name: Run Checks

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  run_ci:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      FORCE_COLOR: 1

    steps:
      - uses: earthly/actions-setup@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: v0.8.15
          use-cache: true
      - uses: actions/checkout@v4
      - name: Docker Login
        run: docker login --username "$DOCKERHUB_USERNAME" --password "$DOCKERHUB_TOKEN"

      - name: Restore Earthly Cache Volume
        id: restore-earthly-cache
        uses: BYK/docker-volume-cache-action/restore@main
        with:
          volumes: earthly-cache
          key: v1-earthly-cache-${{ runner.os }}-${{ hashFiles('**/Earthfile') }}
          restore-keys: |
            v1-earthly-cache-${{ runner.os }}-

      - name: Run checks
        run: |
          earthly config global.buildkit_max_parallelism 1
          earthly --ci --github-annotations +all

      
      - name: Prune earthly cache
        run: earthly prune --size 40GB
      - name: Save Earthly Cache Volume
        uses: BYK/docker-volume-cache-action/save@main
        with:
          key: ${{ steps.restore-earthly-cache.outputs.cache-primary-key }}
          volumes: earthly-cache
