name: Run Checks

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  full_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up rust nighly
        run: rustup override set nightly
      
      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@v1.12.3

      - name: Install just
        run: cargo binstall -y just
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Install deps
        run: just dev_deps
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Install wasm32
        run: rustup target add wasm32-unknown-unknown

      - name: Install rust-analyzer
        run: rustup component add rust-analyzer

      - name: Install rust-src
        run: rustup component add rust-src

      - name: Install rust-fmt
        run: rustup component add rustfmt

      - name: Install clippy
        run: rustup component add clippy

      - name: Install wasm-opt
        run: | 
          sudo apt-get update
          sudo apt-get install -y binaryen

      - name: Health Check Deps
        run: just health_check

      - name: run tests
        run: | 
            just test_native
            just test_web
            # Doesnt like github actions it seems
            # just integration_tests_dev
            # just integration_tests_build
            # just project_gen_test
        
      - name: run checks
        run: |
            just check
            just check_docs
            just check_deps
