name: Run Checks

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  run_ci:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      FORCE_COLOR: 1

    steps:
      - uses: earthly/actions-setup@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: v0.8.15
          use-cache: true
      - uses: actions/checkout@v3
      - name: Docker Login
        run: docker login --username "$DOCKERHUB_USERNAME" --password "$DOCKERHUB_TOKEN"
      - name: Run checks
        run: |
          earthly config buildkit_max_parallelism 1
          earthly --ci --github-annotations +all
